backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "Sandwiches" # Used in routes, e.g., /admin/collections/blog
    label: "Sandwiches" # Used in the UI
    folder: "Products/Sandwiches" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "Featured Image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
